### ISSUE TITLE
Wallet deleted when container restarted?

### ISSUE THREAD

**Issue by jonathan-daniel** [osminogin/docker-electrum-daemon#10]
Hello, 

I am new to docker, I set this image up like this in docker-compose.yml:

```
electrum:
    image: osminogin/electrum-daemon:3.3.8
    expose:
      - 7000
    env_file:
      - .electrum.dev
    volumes:
      - electrum-data:/data
volumes:
  electrum-data:
```

But when I run electrum create in the container, it creates the wallet in .electrum/wallets but when I restart its gone, how can I make it persist? From what i've seen there is no simple way to make the anonymous volume re-use the older ones
